export enum APIControllers {
  Account = 'funaccount',
  Profile = 'Profile',
  // Deck = 'Deck',
  // MemoryCard = 'MemoryCard'
  // Group = 'Group',
  // IncomeOperationCategory = 'IncomeOperationCategory',
  // Invite = 'Invite',
  // MoneyOperation = 'MoneyOperation',
  // OutcomeOperationCategory = 'OutcomeOperationCategory',
  // Purse = 'Purse',
  User = 'User',
  Folder = 'Folder',
  Desk = 'Desk',
  DeskAction = 'DeskAction',
  FolderTrashbin = 'FolderTrashbin',
  DeskTrashbin = 'DeskTrashbin',
  Card = 'Card',
  CardConnection = 'CardConnection',
}
